Update action.yml

diff --git a/.github/actions/build_and_notify/action.yml b/.github/actions/build_and_notify/action.yml
--- a/.github/actions/build_and_notify/action.yml
+++ b/.github/actions/build_and_notify/action.yml
@@ -25,14 +25,17 @@ runs:
       uses: actions/checkout@v2
 
     - name: Set error flag if any step fails
-     id: error
-     shell: bash
-     run: echo "Error occurred"
-     if: ${{ failure() }}
+      shell: bash
+      id: error
+      run: |
+        if [ -n "$?" ]; then
+          echo "Error occurred"
+          exit 1
+        fi
 
     - name: Get commit information
-      id: commit_info
       shell: bash
+      id: commit_info
       run: |
         COMMIT_HASH=$(git rev-parse HEAD)
         BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
@@ -40,24 +43,20 @@ runs:
         echo "::set-output name=branch_name::$BRANCH_NAME"
 
     - name: Set success flag if all steps pass
-      id: success
       shell: bash
+      id: success
       run: echo "All steps passed"
-      if: ${{ success() }}
 
     - name: Send notification to Microsoft Teams
-      shell: bash
       run: |
-        # Get the GitHub workflow run URL
         JOB_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
         
-        # Determine the job status
-        if [ -n "${{ steps.error }}" ]; then
+        if [ -n "${{ steps.error.outputs.result }}" ]; then
           status="FAIL ❌"
           color="attention"
           mentionedId="${{ inputs.error-mention-id }}"
           mentionedName="${{ inputs.error-mention-name }}"
-        elif [ -n "${{ steps.success }}" ]; then
+        elif [ -n "${{ steps.success.outputs.result }}" ]; then
           status="PASS ✅"
           color="good"
           mentionedId="${{ inputs.success-mention-id }}"
@@ -67,17 +66,11 @@ runs:
           color="default"
         fi
         
-        # Get the commit information from previous step
-        COMMIT_HASH=${{ steps.commit_info.outputs.commit_hash }}
-        BRANCH_NAME=${{ steps.commit_info.outputs.branch_name }}
-        
-        # Get the repository URL
+        COMMIT_HASH="${{ steps.commit_info.outputs.commit_hash }}"
+        BRANCH_NAME="${{ steps.commit_info.outputs.branch_name }}"
         REPO_URL="[${{ github.repository }}](${{ github.event.repository.html_url }})"
-        
-        # Get the build number
         BUILD_NUMBER="${{ github.run_number }}"
         
-        # Generate the payload for the notification
         payload='{
           "type": "message",
           "attachments": [
@@ -143,6 +136,5 @@ runs:
             }
           ]
         }'
-                
-        # Send the payload to Microsoft Teams
+
         echo "$payload" | curl -X POST -H 'Content-Type: application/json' -d @- 'https://amdcloud.webhook.office.com/webhookb2/133d4f16-689b-4281-a94b-44725b948c77@3dd8961f-e488-4e60-8e11-a82d994e183d/IncomingWebhook/20c43fc799fd49e9813582813c638323/f9e22351-f1c9-494f-88c5-8e04accf2ffe'
